# Generated by Django 4.2 on 2023-04-20 03:00

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('project_stage', models.CharField(choices=[('UP', 'Unrecognised Potential'), ('HM', 'Historical Mine'), ('EM', 'Evidence of Mineralization'), ('OR', 'Ore Grades Present'), ('MR', 'Multiple Ore Grade Intersections'), ('RS', 'Resources'), ('EF', 'Extractable Feasibility'), ('OTHER', 'Other')], default='UP', max_length=13)),
                ('estimated_resources', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource_type', models.CharField(choices=[('INDICATED', 'Indicated'), ('INFERRED', 'Inferred'), ('MEASURED', 'Measured'), ('EXPLORATION', 'Exploration Target'), ('OTHER', 'Other'), ('NONE', 'None')], default='INDICATED', max_length=22)),
                ('exploration_upside', models.TextField(blank=True, null=True)),
                ('regional_deposits', models.TextField(blank=True, null=True)),
                ('ownership', models.TextField(blank=True, null=True)),
                ('permit_type', models.CharField(choices=[('EPM', 'Exploration Permit'), ('MDL', 'Mineral Development Licence'), ('ML', 'Mining Lease'), ('IN', 'Infrastructure Permit'), ('MISC', 'Miscellaneous Licence')], default='EPM', max_length=24)),
                ('permit_number', models.CharField(blank=True, max_length=200, null=True)),
                ('main_commodity', models.CharField(blank=True, max_length=200, null=True)),
                ('other_commodities', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('GF', 'Greenfield Project'), ('BF', 'Brownfield Project'), ('OTHER', 'Other')], default='BF', max_length=13)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_fields', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, default=list, null=True, size=None)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_posted',),
            },
        ),
    ]
