# Generated by Django 4.2 on 2023-04-13 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('project_stage', models.CharField(choices=[('UP', 'Unrecognised Potential'), ('HM', 'Historical Mine'), ('EM', 'Evidence of Mineralization'), ('OR', 'Ore Grades Present'), ('MR', 'Multiple Ore Grade Intersections'), ('RS', 'Resources'), ('EF', 'Extractable Feasibility')], max_length=3)),
                ('estimated_resources', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource_type', models.CharField(choices=[('INDICATED', 'Indicated'), ('INFERRED', 'Inferred'), ('MEASURED', 'Measured'), ('EXPLORATION', 'Exploration Target'), ('NONE', 'None')], max_length=12)),
                ('exploration_upside', models.TextField(blank=True, null=True)),
                ('regional_deposits', models.TextField(blank=True, null=True)),
                ('ownership', models.TextField(blank=True, null=True)),
                ('permit_type', models.CharField(choices=[('EPM', 'Exploration Permit'), ('MDL', 'Mineral Development Licence'), ('ML', 'Mining Lease'), ('IN', 'Infrastructure Permit'), ('MISC', 'Miscellaneous Licence')], max_length=4)),
                ('permit_number', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
            ],
        ),
    ]
