# Generated by Django 4.2 on 2023-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
