# Generated by Django 4.2 on 2023-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_location_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='permit_type',
            field=models.CharField(choices=[('EPM', 'Exploration Permit'), ('MDL', 'Mineral Development Licence'), ('ML', 'Mining Lease'), ('IN', 'Infrastructure Permit'), ('MISC', 'Miscellaneous Licence')], default='EPM', max_length=14),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(choices=[('UP', 'Unrecognised Potential'), ('HM', 'Historical Mine'), ('EM', 'Evidence of Mineralization'), ('OR', 'Ore Grades Present'), ('MR', 'Multiple Ore Grade Intersections'), ('RS', 'Resources'), ('EF', 'Extractable Feasibility'), ('OTHER', 'Other')], default='UP', max_length=13),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_type',
            field=models.CharField(choices=[('INDICATED', 'Indicated'), ('INFERRED', 'Inferred'), ('MEASURED', 'Measured'), ('EXPLORATION', 'Exploration Target'), ('OTHER', 'Other'), ('NONE', 'None')], default='INDICATED', max_length=12),
        ),
    ]
