# Generated by Django 4.2 on 2023-04-13 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_miningproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
