# Generated by Django 4.2 on 2023-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description_alter_project_permit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_fields',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
