# Generated by Django 4.2 on 2023-04-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_bio_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
