# Generated by Django 4.2 on 2023-04-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
