# Generated by Django 4.2 on 2023-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
